version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    hostname: "zookeeper"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    expose:
      - 9092
    hostname: "kafka"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cadastro:
    image: cadastro
    container_name: cadastro
    build: .
    depends_on:
      - kafka
    ports:
      - "5001:5000"
    hostname: "cadastro"
    volumes:
      - "./servicos/cadastro:/workdir"
    command: python3 /workdir/servico.py

  desbloqueio:
    image: desbloqueio
    container_name: desbloqueio
    build: .
    depends_on:
      - kafka
    hostname: "desbloqueio"
    volumes:
      - "./servicos/desbloqueio:/workdir"
    command: python3 /workdir/servico.py

  listagem:
    image: listagem
    container_name: listagem
    build: .
    depends_on:
      - kafka
    hostname: "listagem"
    volumes:
      - "./servicos/listagem:/workdir"
    command: python3 /workdir/servico.py

  status:
    image: status
    container_name: status
    build: .
    depends_on:
      - kafka
    hostname: "status"
    volumes:
      - "./servicos/status:/workdir"
    command: python3 /workdir/servico.py
